# Generated by Django 5.0.3 on 2024-03-06 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_remove_car_state_alter_car_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='milage',
            new_name='km',
        ),
        migrations.RemoveField(
            model_name='car',
            name='miles',
        ),
    ]
